{
 "title": "Bcc P2P Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Negotiated duplex connections (including DuplexState connections)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_connectionManager_duplexConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Hot peers (active connections)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_peerSelection_hot",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Remote peers that have the local peer as hot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_inbound_governor_hot",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Negotiated unidirectional connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_connectionManager_unidirectionalConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Warm peers (established but not active connection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_peerSelection_warm",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Remote peers that have the local peer as warm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_inbound_governor_warm",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_connectionManager_incomingConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cold peers (known but without established connection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_peerSelection_cold",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Network usefulness factor (tm): ratio of blocks served in last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(bcc_node_metrics_served_block_latest_count[1h])/rate(bcc_node_metrics_blockNum_int[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Outbound connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_connectionManager_outgoingConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within one second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_blockfetchclient_blockdelay_cdfOne",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block propagation delay (seconds, 5 min sliding average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(bcc_node_metrics_blockfetchclient_blockdelay_s[5m])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connections relevant for pruning",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_connectionManager_prunableConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within two seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_blockfetchclient_blockdelay_cdfTwo",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Ratio of late (>5s delay) blocks in the last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(bcc_node_metrics_blockfetchclient_lateblocks[1h])/rate(bcc_node_metrics_blockNum_int[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within five seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_blockfetchclient_blockdelay_cdfFive",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}