{
 "title": "Cole-Reboot Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "TCP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Europe (Frankfurt) TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-a-.*|rel-a-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "US East (Ohio) TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-b-.*|rel-b-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Asia Pacific (Singapore) TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-c-.*|rel-c-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Europe (London) TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-d-.*|rel-d-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "US West (N. California) TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-e-.*|rel-e-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Asia Pacific (Tokyo) TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-f-.*|rel-f-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Edge Node CPU% and Free Mem%", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Edge Node CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{alias=~\"e-.*|rel-.*\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Edge Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=~\"e-.*|rel-.*\"} / node_memory_MemTotal_bytes{alias=~\"e-.*|rel-.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Edge Node Region Aggregate Bandwidth and BlockNum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Region Aggregate Bandwidth Comparison (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-a-.*|rel-a-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Frankfurt Egress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-a-.*|rel-a-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Frankfurt Ingress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-b-.*|rel-b-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Ohio Egress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-b-.*|rel-b-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Ohio Ingress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-c-.*|rel-c-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Singapore Egress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-c-.*|rel-c-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Singapore Ingress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-d-.*|rel-d-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "London Egress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-d-.*|rel-d-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "London Ingress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-e-.*|rel-e-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "N. California Egress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-e-.*|rel-e-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "N. California Ingress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-f-.*|rel-f-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Tokyo Egress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-f-.*|rel-f-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Tokyo Ingress"
    }
   ]
  },
  {
   "title": "EdgeNode BlockNum",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bcc_node_ChainDB_metrics_blockNum_int{alias=~\"e-.*|rel-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Edge Node Egress Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Europe (Frankfurt) Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-a-.*|rel-a-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "US East (Ohio) Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-b-.*|rel-b-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Asia Pacific (Singapore) Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-c-.*|rel-c-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Europe (London) Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-d-.*|rel-d-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "US West (N. California) Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-e-.*|rel-e-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Asia Pacific (Tokyo) Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-f-.*|rel-f-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Edge Node Ingress Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Europe (Frankfurt) Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-a-.*|rel-a-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "US East (Ohio) Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-b-.*|rel-b-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Asia Pacific (Singapore) Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-c-.*|rel-c-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Europe (London) Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-d-.*|rel-d-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "US West (N. California) Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-e-.*|rel-e-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Asia Pacific (Tokyo) Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-f-.*|rel-f-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}