{
 "title": "Bcc: Application metrics v2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Node Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(bcc_node_cli_version_major{alias!~\".*-dr-.*\"})",
     "legendFormat": "Node Major Version:"
    },
    {
     "expr": "min(bcc_node_cli_version_minor{alias!~\".*-dr-.*\"})",
     "legendFormat": "Node Minor Version:"
    },
    {
     "expr": "min(bcc_node_cli_version_patch{alias!~\".*-dr-.*\"})",
     "legendFormat": "Node Patch Version:"
    }
   ]
  },
  {
   "title": "Current Protocol/Era",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(bcc_node_config_isBcc{alias!~\".*-dr-.*\"})",
     "legendFormat": "isBccProtocol"
    },
    {
     "expr": "min(bcc_node_config_isSophie{alias!~\".*-dr-.*\"})",
     "legendFormat": "isSophieEra"
    },
    {
     "expr": "min(bcc_node_config_isCole{alias!~\".*-dr-.*\"})",
     "legendFormat": "isColeEra"
    }
   ]
  },
  {
   "title": "Current Protocol Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(bcc_node_protocol_protocolVersion_major)",
     "legendFormat": "Major protocol version"
    },
    {
     "expr": "min(bcc_node_protocol_protocolVersion_minor)",
     "legendFormat": "Minor protocol version"
    }
   ]
  },
  {
   "title": "Bcc Last Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bcc_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    { "expr": "bcc_node_metrics_blockNum_int", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Bcc Slot Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bcc_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    },
    { "expr": "bcc_node_metrics_slotNum_int", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Bcc Chain Density",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bcc_node_ChainDB_metrics_density_real / on(alias) bcc_node_genesis_activeSlotsCoeff * 100",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "bcc_node_metrics_density_real / on(alias) bcc_node_genesis_activeSlotsCoeff * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Bcc Last Block Epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bcc_node_ChainDB_metrics_epoch_int",
     "legendFormat": "{{alias}}"
    },
    { "expr": "bcc_node_metrics_epoch_int", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "graph",
   "description": "Calculated at a 1 hr averaging window",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(bcc_node_metrics_Forge_node_is_leader_int[1h])/rate(bcc_node_ChainDB_metrics_slotNum_int[1h])) / on(alias) bcc_node_genesis_activeSlotsCoeff",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum((rate(bcc_node_metrics_Forge_node_is_leader_int[1h])/rate(bcc_node_ChainDB_metrics_slotNum_int[1h])) / on(alias) bcc_node_genesis_activeSlotsCoeff)",
     "legendFormat": "Total led slots"
    },
    {
     "expr": "(rate(bcc_node_metrics_Forge_node_is_leader_int[1h])/rate(bcc_node_metrics_slotNum_int[1h])) / on(alias) bcc_node_genesis_activeSlotsCoeff",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum((rate(bcc_node_metrics_Forge_node_is_leader_int[1h])/rate(bcc_node_metrics_slotNum_int[1h])) / on(alias) bcc_node_genesis_activeSlotsCoeff)",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_metrics_Forge_forged_int - bcc_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "bcc_node_metrics_Forge_forged_int - bcc_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Bcc Last Block Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bcc_node_ChainDB_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "bcc_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Missed slots rate (slots/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bcc_node_metrics_slotsMissedNum_int[1m])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Bcc-ping P95 latency (ms) - last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95, bcc_ping_latency_ms[1h:1m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg(quantile_over_time(0.95, bcc_ping_latency_ms{class=~\".*relay\"}[1h:1m]))",
     "legendFormat": "All relays"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bcc_node_ChainDB_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(bcc_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block utilization (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(bcc_node_metrics_blockfetchclient_blocksize[15m]) / (64*1024))",
     "legendFormat": "15 min average"
    },
    {
     "expr": "quantile(0.5, bcc_node_metrics_blockfetchclient_blocksize / (64*1024))",
     "legendFormat": "last"
    },
    {
     "expr": "avg(avg_over_time(bcc_node_metrics_blockfetchclient_blocksize[4h]) / (64*1024))",
     "legendFormat": "4h average"
    }
   ]
  },
  {
   "title": "Mempool Txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(bcc_node_metrics_txsInMempool_int[30m]))",
     "legendFormat": "30 min average"
    }
   ]
  },
  {
   "title": "KES Periods Remaining",
   "type": "graph",
   "description": "KES periods remaining",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_Forge_metrics_remainingKESPeriods_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "bcc_node_metrics_remainingKESPeriods_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Current KES Period",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(bcc_node_Forge_metrics_currentKESPeriod_int)"
    },
    {
     "expr": "avg(bcc_node_metrics_currentKESPeriod_int)"
    }
   ]
  },
  {
   "title": "KES Time Remaining (Alternate Method)",
   "type": "graph",
   "description": "Secondary method of calculating the KES time remaining until expiration",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(bcc_node_genesis_slotLength * (bcc_node_genesis_slotsPerKESPeriod * ((bcc_node_decode_kesCreatedPeriod > -1) + bcc_node_genesis_maxKESEvolutions)) - on(alias) (bcc_node_genesis_slotLength * on(alias) bcc_node_ChainDB_metrics_slotNum_int))",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(bcc_node_genesis_slotLength * (bcc_node_genesis_slotsPerKESPeriod * ((bcc_node_decode_kesCreatedPeriod > -1) + bcc_node_genesis_maxKESEvolutions)) - on(alias) (bcc_node_genesis_slotLength * on(alias) bcc_node_metrics_slotNum_int))",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(bcc_node_ChainDB_metrics_slotNum_int[600s])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "1/rate(bcc_node_metrics_slotNum_int[600s])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "KES Time Remaining Until Expiration",
   "type": "graph",
   "description": "KES time remaining",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bcc_node_Forge_metrics_remainingKESPeriods_int * on(alias) bcc_node_genesis_slotsPerKESPeriod * on(alias) bcc_node_genesis_slotLength",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "bcc_node_metrics_remainingKESPeriods_int * on(alias) bcc_node_genesis_slotsPerKESPeriod * on(alias) bcc_node_genesis_slotLength",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Decentralization Parameter (d)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_node_protocol_decentralisationParam >= 0",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time()-node_boot_time_seconds)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Bcc Service Restarts Per Hour",
   "type": "graph",
   "description": "Shows how many times bcc related services have been restarted within a 1 hour lookback window",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase(node_systemd_unit_state{name=~\"bcc.*|cole.*|explorer.*\",state=\"active\"}[1h:10s])) > 0",
     "legendFormat": "{{alias}}-{{name}}"
    }
   ]
  },
  {
   "title": "Node Memory Free (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s])) * 8",
     "legendFormat": "Aggregate cluster ingress (received)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Aggregate cluster egress (transmit)"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Faucet (BCC)",
   "type": "graph",
   "description": "Remaining faucet funds in BCC",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bcc_faucet_metrics_value_available / 1e6",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}