{
 "title": "Explorer Database",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Chain Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "db_block_height", "legendFormat": "DB" },
    { "expr": "remote_tip_height", "legendFormat": "Node To Client Tip" },
    {
     "expr": "bcc_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "Node {{alias}}"
    },
    {
     "expr": "bcc_node_metrics_ChainDB_blockNum_int",
     "legendFormat": "Node {{alias}}"
    }
   ]
  },
  {
   "title": "blocks/minute over last 5mins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(db_block_height[150s])*60", "legendFormat": "DB" },
    {
     "expr": "rate(remote_tip_height[150s])*60",
     "legendFormat": "Node To Client Tip"
    },
    {
     "expr": "rate(bcc_node_ChainDB_metrics_blockNum_int[150s])*60",
     "legendFormat": "Node {{alias}}"
    },
    {
     "expr": "rate(bcc_node_metrics_ChainDB_blockNum_int[150s])*60",
     "legendFormat": "Node {{alias}}"
    }
   ]
  },
  {
   "title": "rts_gc_gc_cpu_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "rate(rts_gc_gc_cpu_ms[1m])", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "rts_gc_num_gcs's/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(rts_gc_num_gcs[1m])", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "rts_gc_current_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rts_gc_current_bytes_used", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "epoch vs rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(cexplorerBlockCount_count/21600)",
     "legendFormat": "epoch"
    },
    {
     "expr": "rate(cexplorerBlockCount_count[5m])",
     "legendFormat": "db blocks/sec"
    },
    {
     "expr": "rate(bcc_node_metrics_ChainDB_blockNum_int[5m])",
     "legendFormat": "node blocks/sec {{alias}}"
    }
   ]
  },
  {
   "title": "TBQueue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "action_queue_length_pre", "legendFormat": "pre-read" },
    { "expr": "action_queue_length_post", "legendFormat": "post-read" },
    { "expr": "action_queue_length_post_write", "legendFormat": "post-write" }
   ]
  },
  {
   "title": "Transactions/min, 5min avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_transactions_inserted[5m])*60"
    }
   ]
  },
  {
   "title": "batches/minute, 5min avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_batches_inserted[5m])*60"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_block_height[5m]) / rate(db_batches_inserted[5m])",
     "legendFormat": "blocks per batch"
    },
    {
     "expr": "rate(db_transactions_inserted[5m]) / rate(db_block_height[5m])",
     "legendFormat": "tx per batch"
    },
    {
     "expr": "rate(db_transactions_inserted[5m]) / rate(db_batches_inserted[5m])",
     "legendFormat": "tx per block"
    }
   ]
  },
  {
   "title": "Complete Epochs in database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(cexplorerBlockCount_count/21600)"
    }
   ]
  }
 ]
}